---
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: micromessage
spec:
    replicas: 5
    selector:
        matchLabels:
            name: micromessage
    template:
        metadata:
            labels:
                name: micromessage
        spec:
            containers:
            - name: application
              image: vosuyak/micromessage
              imagePullPolicy: IfNotPresent
              ports:
                  - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: micromessage-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: micromessage